import{a as p,S as y,i as l}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const L="50677647-868d585e754b962a191c6dabd",w="https://pixabay.com/api/";async function b(o,r){const e={key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{return(await p.get(w,{params:e})).data}catch{throw new Error("Error fetching data from Pixabay API")}}const u=document.querySelector(".gallery"),f=document.querySelector(".load-more"),m=document.querySelector(".loader"),v=new y(".gallery a",{captionsData:"alt",captionDelay:250});function S(o){const r=o.map(e=>`
    <div class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        <p><strong>Downloads:</strong> ${e.downloads}</p>
        <p><strong>Comments:</strong> ${e.comments}</p>
      </div>
    </div>
  `).join("");u.insertAdjacentHTML("beforeend",r),v.refresh()}function q(){u.innerHTML=""}function C(){m.classList.remove("is-hidden")}function P(){m.classList.add("is-hidden")}function B(){f.classList.remove("is-hidden")}function g(){f.classList.add("is-hidden")}const M=document.querySelector(".form"),$=document.querySelector(".load-more");let i,a=1;const d=15;M.addEventListener("submit",o=>{o.preventDefault(),g(),q(),i=o.target.elements["search-text"].value.trim(),i&&(a=1,h(i))});$.addEventListener("click",o=>{g(),a++,h(i),E()});async function h(o){C();try{const r=await b(o,a,d),e=r.hits;e&&e.length>0?(S(e),a>=Math.ceil(r.totalHits/d)?l.show({title:"ℹ️",message:"We're sorry, but you've reached the end of search results.",messageColor:"white",titleColor:"white",backgroundColor:"#4CAF50",position:"topRight"}):B()):l.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",titleColor:"white",backgroundColor:"#ef4040",position:"topRight"})}catch(r){console.error(r)}finally{P()}}function E(){const o=document.querySelector(".gallery-item");o&&setTimeout(()=>{scrollBy({top:o.getBoundingClientRect().height*2,left:0,behavior:"smooth"})},200)}
//# sourceMappingURL=index.js.map
