import{a as h,S as p,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const L="50677647-868d585e754b962a191c6dabd",w="https://pixabay.com/api/";async function v(r,t){const o={key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{return(await h.get(w,{params:o})).data}catch{throw new Error("Error fetching data from Pixabay API")}}const f=document.querySelector(".gallery"),m=document.querySelector(".load-more"),y=document.querySelector(".loader"),b=new p(".gallery a",{captionsData:"alt",captionDelay:250});function q(r){const t=r.map(o=>`
    <div class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${o.likes}</p>
        <p><strong>Views:</strong> ${o.views}</p>
        <p><strong>Downloads:</strong> ${o.downloads}</p>
        <p><strong>Comments:</strong> ${o.comments}</p>
      </div>
    </div>
  `).join("");f.insertAdjacentHTML("beforeend",t),b.refresh()}function S(){f.innerHTML=""}function B(){y.classList.remove("hidden")}function P(){y.classList.add("hidden")}function $(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}const E=document.querySelector(".form"),M=document.querySelector(".load-more");let d="",i=1,u=0;E.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.target.elements.searchQuery.value.trim(),!d){a.error({message:"Please enter a search term!"});return}i=1,S(),l(),await g()});M.addEventListener("click",async()=>{i+=1,await g(!0)});async function g(r=!1){try{B();const t=await v(d,i);if(t.hits.length===0){a.info({message:"No images found. Try a different query."}),l();return}q(t.hits),u=t.totalHits,i*15>=u?(l(),a.info({message:"We're sorry, but you've reached the end of search results."})):$(),r&&A()}catch{a.error({message:"Failed to fetch images. Try again later."})}finally{P()}}function A(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
